<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ZVFfLws' shared service.

return $this->privates['.service_locator.ZVFfLws'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'secteurRepository' => ['privates', 'App\\Repository\\SecteurRepository', 'getSecteurRepositoryService.php', true],
]);
