<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..ET0_px' shared service.

return $this->privates['.service_locator..ET0_px'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'materiel' => ['privates', '.errored..service_locator..ET0_px.App\\Entity\\Materiel', NULL, 'Cannot autowire service ".service_locator..ET0_px": it references class "App\\Entity\\Materiel" but no such service exists.'],
]);
