<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tGAB48v' shared service.

return $this->privates['.service_locator.tGAB48v'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'secteur' => ['privates', '.errored..service_locator.tGAB48v.App\\Entity\\Secteur', NULL, 'Cannot autowire service ".service_locator.tGAB48v": it references class "App\\Entity\\Secteur" but no such service exists.'],
]);
