<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.U36d7ct.App\Entity\Demande' shared service.

include_once $this->targetDirs[3].'\\src\\Entity\\Demande.php';

return $this->privates['.errored..service_locator.U36d7ct.App\Entity\Demande'] = new \App\Entity\Demande();
