<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.U36d7ct' shared service.

return $this->privates['.service_locator.U36d7ct'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'demande' => ['privates', '.errored..service_locator.U36d7ct.App\\Entity\\Demande', NULL, 'Cannot autowire service ".service_locator.U36d7ct": it references class "App\\Entity\\Demande" but no such service exists.'],
]);
